#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mal.Xamarin.Infra.Android.DevApp.Resource", IsApplication=true)]

namespace Mal.Xamarin.Infra.Android.DevApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Mal.Xamarin.Infra.Android.Resource.Id.progressBar = global::Mal.Xamarin.Infra.Android.DevApp.Resource.Id.progressBar;
			global::Mal.Xamarin.Infra.Android.Resource.Layout.ListViewBusyIndicatorFooter = global::Mal.Xamarin.Infra.Android.DevApp.Resource.Layout.ListViewBusyIndicatorFooter;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int black = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int blue_200 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int blue_300 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int blue_500 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int blue_600 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int blue_900 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int white = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int icon = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int lazylistitem_edittitle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int lazylistitem_title = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int listButton = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int list_items = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int listviewtemplate_check = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int listviewtemplate_title = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int myButton = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int progressBar = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LazyList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LazyListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LazyListItemTemplate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListViewBusyIndicatorFooter = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Material_Light_ColoredBar = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
